### ISSUE TITLE
Reset multiplier when hitting obstacle

### ISSUE THREAD

**Issue by pserwylo** [pserwylo/beat-game#38]
Not just when hitting the ground.

**Comment by Glitchy-Tozier** [comment]
I feel like it still doesn't reset all the way sometimes.
I saw it return to 1.5 a couple of times i think.

**Comment by pserwylo** [comment]
It's worth noting that in more recent versions, the counter doesn't even show fractions of a multiplier any more, so this wont be an issue any more in v0.3.0 or above.

**Comment by Glitchy-Tozier** [comment]
Do those fractions still exist or are the multipliers straight up bigger?
